version: "2"
run:
  timeout: 5m
linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exptostd
    - forbidigo
    - forcetypeassert
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
    - nolintlint
  exclusions:
    generated: lax
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: false
      colors: false
