// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Hero struct {
	ID             []byte    `json:"id"`
	AncestryName   string    `json:"ancestry_name"`
	ClassName      string    `json:"class_name"`
	Motivation     string    `json:"motivation"`
	Origin         string    `json:"origin"`
	BackgroundName string    `json:"background_name"`
	Quirks         string    `json:"quirks"`
	CreatedAt      time.Time `json:"created_at"`
}
