// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateHero(ctx context.Context, arg CreateHeroParams) (Hero, error)
	DeleteHero(ctx context.Context, id []byte) error
	GetHero(ctx context.Context, id []byte) (Hero, error)
	ListHeroes(ctx context.Context) ([]Hero, error)
}

var _ Querier = (*Queries)(nil)
