// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const createHero = `-- name: CreateHero :one
INSERT INTO heroes (
    id, ancestry_name, class_name, motivation, origin, background_name, quirks
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, ancestry_name, class_name, motivation, origin, background_name, quirks, created_at
`

type CreateHeroParams struct {
	ID             []byte `json:"id"`
	AncestryName   string `json:"ancestry_name"`
	ClassName      string `json:"class_name"`
	Motivation     string `json:"motivation"`
	Origin         string `json:"origin"`
	BackgroundName string `json:"background_name"`
	Quirks         string `json:"quirks"`
}

func (q *Queries) CreateHero(ctx context.Context, arg CreateHeroParams) (Hero, error) {
	row := q.db.QueryRowContext(ctx, createHero,
		arg.ID,
		arg.AncestryName,
		arg.ClassName,
		arg.Motivation,
		arg.Origin,
		arg.BackgroundName,
		arg.Quirks,
	)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.AncestryName,
		&i.ClassName,
		&i.Motivation,
		&i.Origin,
		&i.BackgroundName,
		&i.Quirks,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHero = `-- name: DeleteHero :exec
DELETE FROM heroes
WHERE id = ?
`

func (q *Queries) DeleteHero(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, deleteHero, id)
	return err
}

const getHero = `-- name: GetHero :one
SELECT id, ancestry_name, class_name, motivation, origin, background_name, quirks, created_at FROM heroes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetHero(ctx context.Context, id []byte) (Hero, error) {
	row := q.db.QueryRowContext(ctx, getHero, id)
	var i Hero
	err := row.Scan(
		&i.ID,
		&i.AncestryName,
		&i.ClassName,
		&i.Motivation,
		&i.Origin,
		&i.BackgroundName,
		&i.Quirks,
		&i.CreatedAt,
	)
	return i, err
}

const listHeroes = `-- name: ListHeroes :many
SELECT id, ancestry_name, class_name, motivation, origin, background_name, quirks, created_at FROM heroes
ORDER BY created_at DESC
`

func (q *Queries) ListHeroes(ctx context.Context) ([]Hero, error) {
	rows, err := q.db.QueryContext(ctx, listHeroes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hero
	for rows.Next() {
		var i Hero
		if err := rows.Scan(
			&i.ID,
			&i.AncestryName,
			&i.ClassName,
			&i.Motivation,
			&i.Origin,
			&i.BackgroundName,
			&i.Quirks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
